pref("extensions.4pda-inspector.interval", 30);
pref("extensions.4pda-inspector.click_action", 1);
pref("extensions.4pda-inspector.button_fontsize", 8);
pref("extensions.4pda-inspector.button_big_fontsize", 12);
pref("extensions.4pda-inspector.button_big", false);
pref("extensions.4pda-inspector.button_bgcolor", '#4474C4');
pref("extensions.4pda-inspector.button_color", '#FFFFFF');
pref("extensions.4pda-inspector.notification_sound", true);
pref("extensions.4pda-inspector.notification_popup", true);